package jpl.simle.domain;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.acls.domain.AclImpl;
import org.springframework.security.acls.domain.ObjectIdentityImpl;
import org.springframework.security.acls.domain.PrincipalSid;
import org.springframework.security.acls.model.MutableAcl;
import org.springframework.security.acls.model.MutableAclService;
import org.springframework.security.acls.model.ObjectIdentity;
import org.springframework.security.acls.model.Permission;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.authority.AuthorityUtils;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionStatus;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.support.TransactionCallback;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.util.Assert;


import jpl.simle.domain.Protocol.Direction;
import jpl.simle.domain.Protocol.NetworkProtocol;

import java.util.Map;
import java.util.HashMap;

import javax.sql.DataSource;

import jpl.simle.service.AuthenticationService;
import jpl.simle.service.LabManagerService;
import jpl.simle.service.impl.AuthenticationServiceImpl;
import jpl.simle.utils.SIMLEUtils;

@Transactional
public class DataSourcePopulator 
{
	@Autowired
	private LabManagerService labManager;
	@Autowired
	private AuthenticationService authenticationService;
	
	private JdbcTemplate template;
	private TransactionTemplate tt;
	private MutableAclService mutableAclService;
	
	private Map<String,Application> applications = new HashMap<String,Application>();
	
	
	private final static String[][] HOSTS = { 
		// address IP, hostname, dnsnames, { applications }
		{ "76.131", "tcc.mugu-el", "el.tcc.mugu", "Environment Logger", "MultiRouter", "TENA", "Environment Logger (BSI)", "Exec Control", "OS Agent", "ClearPath" },
		{ "76.132", "tcc.mugu-tc", "tc.tcc.mugu", "TENA", "OS Agent", "ClearPath" },
		{ "76.133", "tcc.mugu.crsp", "crsp.tcc.mugu", "TENA", "OS Agent", "ClearPath" },
		{ "76.134", "tcc.mugu-tcm", "tcm.tcc.mugu", "TENA", "OS Agent", "ClearPath" },
		{ "76.135", "tcc.mugu-jmesssvr", "jimessvr.tcc.mugu", "TENA", "OS Agent", "ClearPath" },
		{ "76.136", "tcc.mugu.ie", "ie.tcc.mugu", "Environment Logger", "Environment Logger (BSI)", "Exec Control", "TENA", "OS Agent", "ClearPath" },
		{ "76.137", "tcc.mugu.jimes1", "jimes1.tcc.mugu", "TENA", "OS Agent", "ClearPath" },
		{ "76.138", "tcc.mugu.jimes2", "jimes2.tcc.mugu", "TENA", "OS Agent", "ClearPath" },
		{ "76.139", "tcc.mugu.jimes3", "jimes3.tcc.mugu", "TENA", "OS Agent", "ClearPath" },
		{ "76.140", "tcc.mugu.vmf", "vmf.tcc.mugu", "TENA", "OS Agent", "ClearPath" },
		{ "76.141", "tcc.mugu.ibs", "ibs.tcc.mugu", "TENA", "OS Agent", "ClearPath" },
		{ "76.142", "tcc.mugu.rdgw", "rdgw.tcc.mugu", "TENA", "OS Agent", "ClearPath" },
		{ "76.143", "tcc.mugu.jimm", "jimm.tcc.mugu", "TENA", "OS Agent", "ClearPath" },
		{ "76.144", "tcc.mugu.jsaf", "jsaf.tcc.mugu", "TENA", "OS Agent", "ClearPath" },
		{ "76.145", "tcc.mugu.ssegw2", "ssegw2.tcc.mugu", "TENA", "OS Agent", "ClearPath" },
		{ "76.146", "tcc.mugu.hpov", "hpov.tcc.mugu", "TENA", "OS Agent", "ClearPath" },
		{ "76.149", "tcc.mugu-jmps", "jmpcs.tcc.mugu", "TENA", "OS Agent", "ClearPath" },
		{ "76.150", "tcc.mugu-trt", "trt.tcc.mugu", "TENA", "OS Agent", "ClearPath" },
		{ "76.151", "tcc.mugu-video", "video.tcc.mugu", "TENA", "OS Agent", "ClearPath" },
		{ "76.152", "asti-1", "astl1.tcc.mugu", "TENA" },
		{ "76.153", "astl-2", "astl2.tcc.mugu", "TENA" },
		{ "76.183", "989-6001", "989-6001" }
	};
	
	public void createACLTables()
	{
	    try
	    {
	        template.execute("DROP TABLE ACL_ENTRY");
	        template.execute("DROP TABLE ACL_ENTRY");
	        template.execute("DROP TABLE ACL_CLASS");
	        template.execute("DROP TABLE ACL_SID");
	    }
	    catch (Exception e) 
	    {
	        System.out.println("Failed to drop tables: " + e.getMessage());
	    }
	    
        template
                .execute("CREATE TABLE ACL_SID("
                        + "ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 100) NOT NULL PRIMARY KEY,"
                        + "PRINCIPAL BOOLEAN NOT NULL,"
                        + "SID VARCHAR_IGNORECASE(100) NOT NULL,"
                        + "CONSTRAINT UNIQUE_UK_1 UNIQUE(SID,PRINCIPAL));");
        template
                .execute("CREATE TABLE ACL_CLASS("
                        + "ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 100) NOT NULL PRIMARY KEY,"
                        + "CLASS VARCHAR_IGNORECASE(100) NOT NULL,"
                        + "CONSTRAINT UNIQUE_UK_2 UNIQUE(CLASS));");
        template
                .execute("CREATE TABLE ACL_OBJECT_IDENTITY("
                        + "ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 100) NOT NULL PRIMARY KEY,"
                        + "OBJECT_ID_CLASS BIGINT NOT NULL,"
                        + "OBJECT_ID_IDENTITY BIGINT NOT NULL,"
                        + "PARENT_OBJECT BIGINT,"
                        + "OWNER_SID BIGINT,"
                        + "ENTRIES_INHERITING BOOLEAN NOT NULL,"
                        + "CONSTRAINT UNIQUE_UK_3 UNIQUE(OBJECT_ID_CLASS,OBJECT_ID_IDENTITY),"
                        + "CONSTRAINT FOREIGN_FK_1 FOREIGN KEY(PARENT_OBJECT)REFERENCES ACL_OBJECT_IDENTITY(ID),"
                        + "CONSTRAINT FOREIGN_FK_2 FOREIGN KEY(OBJECT_ID_CLASS)REFERENCES ACL_CLASS(ID),"
                        + "CONSTRAINT FOREIGN_FK_3 FOREIGN KEY(OWNER_SID)REFERENCES ACL_SID(ID));");
        template
                .execute("CREATE TABLE ACL_ENTRY("
                        + "ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 100) NOT NULL PRIMARY KEY,"
                        + "ACL_OBJECT_IDENTITY BIGINT NOT NULL,ACE_ORDER INT NOT NULL,SID BIGINT NOT NULL,"
                        + "MASK INTEGER NOT NULL,GRANTING BOOLEAN NOT NULL,AUDIT_SUCCESS BOOLEAN NOT NULL,"
                        + "AUDIT_FAILURE BOOLEAN NOT NULL,CONSTRAINT UNIQUE_UK_4 UNIQUE(ACL_OBJECT_IDENTITY,ACE_ORDER),"
                        + "CONSTRAINT FOREIGN_FK_4 FOREIGN KEY(ACL_OBJECT_IDENTITY) REFERENCES ACL_OBJECT_IDENTITY(ID),"
                        + "CONSTRAINT FOREIGN_FK_5 FOREIGN KEY(SID) REFERENCES ACL_SID(ID));");
        template
                .execute("CREATE UNIQUE INDEX IX_AUTH_USERNAME ON AUTHORITIES(USERNAME,AUTHORITY)");
	}

	public void init() throws Exception
	{
	    createACLTables();
	    
	    String salt = SIMLEUtils.getRandomHexString(32);
	    
	    
	    // create ITEC user
	    // username: itecuser password: password
		SIMLEUser user = new SIMLEUser();
		user.setUsername("itecuser");
		user.setPassword(authenticationService.encryptPassword("password", salt));
		user.setSalt(salt);
		user.setEnabled(true);
		
		SIMLEGroup group = new SIMLEGroup();
		group.setGroupName("itec");
		
		group.persist();
		
		user.setGroup(group);
		
		Authority roleUser = new Authority();
		roleUser.setUsername(user.getUsername());
		roleUser.setAuthority(Authority.AuthorityTypes.ROLE_USER);
		
		user.persist();
		roleUser.persist();
		
		// create itec admin user
		// username: itecadmin password: password
		
		SIMLEUser adminUser = new SIMLEUser();
		adminUser.setUsername("itecadmin");
		adminUser.setPassword(authenticationService.encryptPassword("password", salt));
		adminUser.setSalt(salt);
		adminUser.setEnabled(true);
		
		group = SIMLEGroup.findSIMLEGroup(group.getId());
		adminUser.setGroup(group);
		
		Authority roleGroupAdmin = new Authority();
		roleGroupAdmin.setUsername(adminUser.getUsername());
		roleGroupAdmin.setAuthority(Authority.AuthorityTypes.ROLE_GROUP_ADMIN);
		
		adminUser.persist();
		roleGroupAdmin.persist();
		
		// create super admin user and admin group
		// username: admin password: password
		
		SIMLEGroup adminGroup = new SIMLEGroup();
		adminGroup.setGroupName(SIMLEGroup.ADMIN_GROUP);
		adminGroup.persist();
		
		SIMLEUser superAdminUser = new SIMLEUser();
		superAdminUser.setUsername("admin");
		superAdminUser.setPassword(authenticationService.encryptPassword("password", salt));
		superAdminUser.setSalt(salt);
		superAdminUser.setEnabled(true);
		
		superAdminUser.setGroup(adminGroup);
		
		Authority roleSuperAdmin = new Authority();
		roleSuperAdmin.setUsername(adminUser.getUsername());
		roleSuperAdmin.setAuthority(Authority.AuthorityTypes.ROLE_ADMIN);
		
		superAdminUser.persist();
		roleSuperAdmin.persist();
		
		
		// setup an authentication context temporarily
		Authentication authRequest = new UsernamePasswordAuthenticationToken("itecadmin", adminUser.getPassword(), AuthorityUtils.createAuthorityList("ROLE_GROUP_ADMIN"));
		SecurityContextHolder.getContext().setAuthentication(authRequest);

		// create a new lab for testing
		Lab lab = new Lab();
		lab.setName("ITEC");
		lab.setGroupName(group.getGroupName());
		lab.setLatitude(new Double(34.1205));
		lab.setLongitude(new Double(-119.1035));
		lab.setDomainName("domain.itec.com");
		
		labManager.saveLab(lab);
		System.out.println();
		System.out.println();System.out.println();System.out.println();System.out.println();
		System.out.println("*********************** " + lab.getId() + "******************************");
		System.out.println();System.out.println();System.out.println();System.out.println();System.out.println();
		Assert.notNull(lab.getId());
		
		addApplications();
		
		for ( String[] hostParams : HOSTS )
		{
		    lab = labManager.findLabById(lab.getId());
			Host host = addHost(lab, hostParams);

			// first 3 describe the host, everything else describes the applications
			for ( int i = 3; i < hostParams.length; ++i )
			{
				Application app = applications.get(hostParams[i]);
				if ( app == null )
				{
					throw new Exception("Could not find application with name: " + hostParams[i]);
				}
				
				labManager.createHostApplicationLink(app, host);
			}
		}

		
		// clear the security context
		SecurityContextHolder.clearContext();
	}
	

    private Host addHost(Lab lab, String[] hostParams)
	{
		Host host = new Host();
		host.setAddressIP(hostParams[0]);
		host.setName(hostParams[1]);
		host.setDnsNames(hostParams[2]);

		return labManager.saveHost(lab, host);
	}
	
	private void addApplications()
	{
		Application envLogger = new Application();
		envLogger.setName("Environment Logger");
		
		labManager.saveApplication(envLogger);
		applications.put(envLogger.getName(), envLogger);
		
		Protocol simpleJ = new Protocol();
		simpleJ.setApplicationProtocol("SimpleJ");
		simpleJ.setNetworkProtocol(NetworkProtocol.UDP);
		simpleJ.setPorts("35600");
		simpleJ.setDirection(Direction.BOTH);
		simpleJ.setDestinationIP("225.25.2.1-254");
		
		labManager.saveProtocol(envLogger, simpleJ);
		
		Protocol vmf = new Protocol();
		vmf.setApplicationProtocol("VMF");
		vmf.setNetworkProtocol(NetworkProtocol.UDP);
		vmf.setPorts("7000");
		vmf.setDirection(Direction.BOTH);
		vmf.setDestinationIP("Local traffic");
		
		labManager.saveProtocol(envLogger, vmf);
		
		Protocol usmtf = new Protocol();
		usmtf.setApplicationProtocol("USMTF");
		usmtf.setNetworkProtocol(NetworkProtocol.UDP);
		usmtf.setPorts("7005");
		usmtf.setDirection(Direction.BOTH);
		usmtf.setDestinationIP("Local traffic");
		
		labManager.saveProtocol(envLogger, usmtf);
		
		Protocol oth = new Protocol();
		oth.setApplicationProtocol("OTH");
		oth.setNetworkProtocol(NetworkProtocol.UDP);
		oth.setPorts("7010");
		oth.setDirection(Direction.BOTH);
		oth.setDestinationIP("225.25.2.1-254");
		
		labManager.saveProtocol(envLogger, oth);
		
		Application multiRouter = new Application();
		multiRouter.setName("MultiRouter");
		
		labManager.saveApplication(multiRouter);
		applications.put(multiRouter.getName(), multiRouter);
		
		simpleJ = new Protocol();
		simpleJ.setApplicationProtocol("SimpleJ");
		simpleJ.setNetworkProtocol(NetworkProtocol.UDP);
		simpleJ.setPorts("35600");
		simpleJ.setDirection(Direction.BOTH);
		simpleJ.setDestinationIP("225.25.2.1-254");
		
		labManager.saveProtocol(multiRouter, simpleJ);
		
		Application tena = new Application();
		tena.setName("TENA");
		
		labManager.saveApplication(tena);
		applications.put("TENA", tena);
		
		
		Protocol tenaTCP = new Protocol();
		tenaTCP.setApplicationProtocol("TENA TCP");
		tenaTCP.setNetworkProtocol(NetworkProtocol.TCP);
		tenaTCP.setPorts("55100,55300-55900/100");
		tenaTCP.setDirection(Direction.BOTH);
		tenaTCP.setDestinationIP("S.253.2");
		tenaTCP.setNotes("Only ports that are a multiple of 100 are assigned in the range of ports");
		
		labManager.saveProtocol(tena, tenaTCP);
		
		Protocol tenaUDP = new Protocol();
		tenaUDP.setApplicationProtocol("TENA UDP");
		tenaUDP.setNetworkProtocol(NetworkProtocol.UDP);
		tenaUDP.setPorts("55200,55600-55900/100");
		tenaUDP.setDirection(Direction.BOTH);
		tenaUDP.setDestinationIP("All TENA nodes");
		tenaTCP.setNotes("Only ports taht are a multiple of 100 are assigned in the range of ports");
		
		labManager.saveProtocol(tena, tenaUDP);
		
		Application environmentLoggerBsi = new Application();
		environmentLoggerBsi.setName("Environment Logger (BSI)");
		
		labManager.saveApplication(environmentLoggerBsi);
		applications.put(environmentLoggerBsi.getName(), environmentLoggerBsi);
		
		Protocol envTena = new Protocol();
		envTena.setApplicationProtocol("TENA");
		envTena.setNetworkProtocol(NetworkProtocol.TCP);
		envTena.setDirection(Direction.BOTH);
		envTena.setPorts("55800");
		envTena.setDestinationIP("S.253.2");
		
		labManager.saveProtocol(environmentLoggerBsi, envTena);
		
		Application execControl = new Application();
		execControl.setName("Exec Control");
		
		labManager.saveApplication(execControl);
		applications.put(execControl.getName(), execControl);
		
		Protocol execTena = new Protocol();
		execTena.setApplicationProtocol("TENA");
		execTena.setNetworkProtocol(NetworkProtocol.TCP);
		execTena.setDirection(Direction.BOTH);
		execTena.setPorts("55801");
		execTena.setDestinationIP("S.253.2");
		
		labManager.saveProtocol(execControl, execTena);
		
		Application osAgent = new Application();
		osAgent.setName("OS Agent");
		
		labManager.saveApplication(osAgent);
		applications.put("OS Agent", osAgent);
		
		Protocol osTimeSync = new Protocol();
		osTimeSync.setApplicationProtocol("Time Sync");
		osTimeSync.setNetworkProtocol(NetworkProtocol.UDP);
		osTimeSync.setPorts("44444");
		osTimeSync.setDirection(Direction.BOTH);
		osTimeSync.setDestinationIP("All OS Agent Nodes");
		
		labManager.saveProtocol(osAgent, osTimeSync);
		
		Protocol osTENA = new Protocol();
		osTENA.setApplicationProtocol("TENA");
		osTENA.setNetworkProtocol(NetworkProtocol.TCP);
		osTENA.setPorts("55817");
		osTENA.setDirection(Direction.BOTH);
		osTENA.setDestinationIP("All OS Agent Nodes");
		
		labManager.saveProtocol(osAgent, osTENA);
		
		Application clearPath = new Application();
		clearPath.setName("ClearPath");
		
		labManager.saveApplication(clearPath);
		applications.put("ClearPath", clearPath);
		
		Protocol clearpathUDP = new Protocol();
		clearpathUDP.setApplicationProtocol("Clearpath UDP");
		clearpathUDP.setNetworkProtocol(NetworkProtocol.UDP);
		clearpathUDP.setPorts("8084");
		clearpathUDP.setDirection(Direction.BOTH);
		clearpathUDP.setDestinationIP("All TENA Nodes");
		
		labManager.saveProtocol(clearPath, clearpathUDP);
		
		Protocol clearpathTCP = new Protocol();
		clearpathTCP.setApplicationProtocol("Clearpath TCP");
		clearpathTCP.setNetworkProtocol(NetworkProtocol.TCP);
		clearpathTCP.setPorts("80,389,443,1099,8087");
		clearpathTCP.setDirection(Direction.BOTH);
		clearpathTCP.setDestinationIP("All TENA Nodes");
		
		labManager.saveProtocol(clearPath, clearpathTCP);
		
	}
	
	@Autowired
	public void setDataSource(DataSource dataSource)
	{
	    this.template = new JdbcTemplate(dataSource);
	}
	
	@Autowired
	public void setPlatformTransactionManager(PlatformTransactionManager platformTransactionManager) 
	{
	    this.tt = new TransactionTemplate(platformTransactionManager);
	}
	
	public void setMutableAclService(MutableAclService mutableAclService) 
	{
	    this.mutableAclService = mutableAclService;
	}
	
	private void grantPermissions(Long labId, String recipientUsername, Permission permission)
	{
	    AclImpl acl = (AclImpl)mutableAclService.readAclById(new ObjectIdentityImpl(Lab.class, new Long(labId)));
	    acl.insertAce(acl.getEntries().size(), permission, new PrincipalSid(recipientUsername), true);
	    updateAclInTransaction(acl);
	}
	
	private void updateAclInTransaction(final MutableAcl acl)
	{
	    tt.execute(new TransactionCallback<Object>() {
	        public Object doInTransaction(TransactionStatus arg0) {
	            mutableAclService.updateAcl(acl);
	            return null;
	        }
	    });
	}
}
